### PR TITLE
Fix testing of external dependencies

### LINKED ISSUE #153: "TypeError: Cannot read property 'isDeclarationFile' of undefined" when using typesVersions
Test branch https://github.com/leonard-thieu/DefinitelyTyped/pull/18

---

When testing the typesVersions feature for `@types/jquery`, I get errors like:

```
The 'expect' rule threw an error in '/home/travis/build/leonard-thieu/DefinitelyTyped/types/jquery/ts3.1/JQueryStatic.d.ts':
TypeError: Cannot read property 'isDeclarationFile' of undefined
    at walk (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/dtslint/bin/rules/expectRule.js:93:20)
    at applyWithFunction.ctx (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/dtslint/bin/rules/expectRule.js:22:62)
    at Rule.AbstractRule.applyWithFunction (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at getFailures (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/dtslint/bin/rules/expectRule.js:22:25)
    at Rule.applyWithProgram (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/dtslint/bin/rules/expectRule.js:24:29)
    at Linter.applyRule (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/linter.js:194:29)
    at /home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/linter.js:139:85
    at Object.flatMap (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/utils.js:151:29)
    at Linter.getAllFailures (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/linter.js:139:32)
    at Linter.lint (/home/travis/build/leonard-thieu/DefinitelyTyped/node_modules/tslint/lib/linter.js:99:33)
```

The process I used was:

* Create a `package.json` with the following contents:
```json
{
    "private": true,
    "types": "index",
    "typesVersions": {
        ">=3.1.0-0": {
            "*": [
                "ts3.1/*"
            ]
        }
    }
}
```
* Create a `ts3.1` directory and copy relevant files into there.
* Remove the header from `ts3.1/index.d.ts`.
* Change `baseUrl` and `typeRoots` in `ts3.1/tsconfig.json` to `../../`.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #153

The problem was that we were relying on `expectRule` to give us compile errors in external dependencies. Now that we have typesVersions, the set of source files included is different between different TS versions. Previously we were relying on `program.getSourceFile(ctx.sourceFile.fileName)!;` to always succeed because `ctx.sourceFile` came from the linter's program, but it always won't work anymore since the linter's program and expectRule's program may come from different TS versions.

The fix is to test external dependencies for errors separately before doing anything with tslint. We will now never lint external dependencies. (Previously we were only linting with expectRule anyway.)

### CODE REVIEW

File: src/lint.ts [hunk 1]
```diff
@@ -3,28 +3,33 @@ import { TypeScriptVersion } from "definitelytyped-header-parser";
...
+import { getProgram, Options as ExpectOptions } from "./rules/expectRule";
 
 import { typeScriptPath } from "./installer";
 import { readJson } from "./util";
 
 export async function lint(dirPath: string, minVersion: TsVersion, maxVersion: TsVersion): Promise<string | undefined> {
-	const lintConfigPath = getConfigPath(dirPath);
 	const tsconfigPath = joinPaths(dirPath, "tsconfig.json");
-	const program = Linter.createProgram(tsconfigPath);
+	const lintProgram = Linter.createProgram(tsconfigPath);
```
Comment (sandersn) [inline src/lint.ts]: why does the lintProgram have a single version but dependencies test 2 versions?

Comment (andy-ms) [reply src/lint.ts]: In `expectRule` we'll test against more versions. For normal lint rules there's no need to test in any version besides `typescript@next`, since that should always be better; for testing older versions we really just care that there are not compile errors.
